// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/header/components/avatar.vue')['default']
    Breadcrumb: typeof import('./src/components/header/components/breadcrumb.vue')['default']
    ChatList: typeof import('./src/components/ChatList/index.vue')['default']
    ChatMessageDisplay: typeof import('./src/components/ChatList/ChatMessageDisplay.vue')['default']
    Checked: typeof import('./src/components/ChatList/icons/Checked.vue')['default']
    ContextMenu: typeof import('./src/components/ChatList/ContextMenu/index.vue')['default']
    DoubleChecked: typeof import('./src/components/ChatList/icons/DoubleChecked.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GroupList: typeof import('./src/components/GroupList/index.vue')['default']
    Hamburger: typeof import('./src/components/header/components/hamburger.vue')['default']
    HeadIndex: typeof import('./src/components/header/headIndex.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MessageItem: typeof import('./src/components/ChatList/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/ChatList/MessageList.vue')['default']
    MessageStack: typeof import('./src/components/ChatList/MessageStack.vue')['default']
    MsgItem: typeof import('./src/components/ChatList/MsgItem/index.vue')['default']
    MsgList: typeof import('./src/components/ChatList/MsgList.vue')['default']
    MsgOption: typeof import('./src/components/ChatList/MsgOption/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserContextMenu: typeof import('./src/components/ChatList/UserContextMenu/index.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export {}
