// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatList: typeof import('./src/components/ChatList/index.vue')['default']
    ChatMessageDisplay: typeof import('./src/components/ChatList/ChatMessageDisplay.vue')['default']
    Checked: typeof import('./src/components/ChatList/icons/Checked.vue')['default']
    CircleChecked: typeof import('./src/components/ChatList/icons/CircleChecked.vue')['default']
    ContextMenu: typeof import('./src/components/ChatList/ContextMenu/index.vue')['default']
    DoubleChecked: typeof import('./src/components/ChatList/icons/DoubleChecked.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Group: typeof import('./src/components/GroupList/component/group.vue')['default']
    GroupList: typeof import('./src/components/GroupList/GroupList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MessageItem: typeof import('./src/components/ChatList/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/ChatList/MessageList.vue')['default']
    MessageStack: typeof import('./src/components/ChatList/MessageStack.vue')['default']
    MsgItem: typeof import('./src/components/ChatList/MsgItem/index.vue')['default']
    MsgList: typeof import('./src/components/ChatList/MsgList.vue')['default']
    MsgOption: typeof import('./src/components/ChatList/MsgOption/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserContextMenu: typeof import('./src/components/ChatList/UserContextMenu/index.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export {}
